# Copyright (c) 2026 Puck Dynasty contributors. All rights reserved.
"""Real NHL franchise records seed data for Puck Dynasty.

Researched 2026-09-28 from Hockey Reference team pages, QuantHockey team
records tables, Wikipedia "List of <team> records" pages, NHL.com, and
official NHL team record books. Every record was verified against at least
one source; nothing is guessed.

Schema:
    FRANCHISE_RECORDS_SEED = {
        "<Team Name>": {
            "season": {"goals": (name, value, "YYYY-YY"),
                       "assists": (...), "points": (...)},
            "career": {"games": (name, value), "goals": (...),
                       "assists": (...), "points": (...)},
            "goalie_season": {"wins": (name, value, "YYYY-YY"),
                              "shutouts": (...)},
            "goalie_career": {"wins": (name, value), "shutouts": (...)},
        },
        ...
    }

Taxonomy / franchise-history rules applied:
- Carolina Hurricanes includes Hartford Whalers (1979-1997).
- Colorado Avalanche includes Quebec Nordiques (1979-1995).
- Dallas Stars includes Minnesota North Stars (1967-1993).
- New Jersey Devils franchise totals are Devils-era (Scouts/Rockies marks
  do not exceed them).
- Calgary Flames includes Atlanta Flames (1972-1980) — leaders unchanged.
- Arizona Coyotes includes the original Winnipeg Jets (1979-1996).
- Current Winnipeg Jets includes Atlanta Thrashers (1999-2011) only.
- Ottawa Senators = modern franchise from 1992 (not the 1917-1934 club).
- Edmonton career totals are NHL-only (WHA excluded).
- Utah Hockey Club is a NEW franchise (2024); its record book starts in
  2024-25 and does NOT inherit Coyotes history. Both "Arizona Coyotes"
  (dormant, historical) and "Utah Hockey Club" are keyed separately.

Ties: where a record is tied, the earliest occurrence is listed.

Career totals for active players are through the 2025-26 season.
"""

FRANCHISE_RECORDS_SEED = {
    "Boston Bruins": {
        "season": {"goals": ("Phil Esposito", 76, "1970-71"),
                   "assists": ("Bobby Orr", 102, "1970-71"),
                   "points": ("Phil Esposito", 152, "1970-71")},
        "career": {"games": ("Ray Bourque", 1518),
                   "goals": ("Johnny Bucyk", 545),
                   "assists": ("Ray Bourque", 1111),
                   "points": ("Ray Bourque", 1506)},
        "goalie_season": {"wins": ("Pete Peeters", 40, "1982-83"),
                          "shutouts": ("Hal Winkler", 15, "1927-28")},
        "goalie_career": {"wins": ("Tuukka Rask", 308),
                          "shutouts": ("Tiny Thompson", 74)},
    },
    "Buffalo Sabres": {
        "season": {"goals": ("Alexander Mogilny", 76, "1992-93"),
                   "assists": ("Pat LaFontaine", 95, "1992-93"),
                   "points": ("Pat LaFontaine", 148, "1992-93")},
        "career": {"games": ("Gilbert Perreault", 1191),
                   "goals": ("Gilbert Perreault", 512),
                   "assists": ("Gilbert Perreault", 814),
                   "points": ("Gilbert Perreault", 1326)},
        "goalie_season": {"wins": ("Ryan Miller", 41, "2009-10"),
                          "shutouts": ("Dominik Hasek", 13, "1997-98")},
        "goalie_career": {"wins": ("Ryan Miller", 284),
                          "shutouts": ("Dominik Hasek", 55)},
    },
    "Detroit Red Wings": {
        "season": {"goals": ("Steve Yzerman", 65, "1988-89"),
                   "assists": ("Steve Yzerman", 90, "1988-89"),
                   "points": ("Steve Yzerman", 155, "1988-89")},
        "career": {"games": ("Gordie Howe", 1687),
                   "goals": ("Gordie Howe", 786),
                   "assists": ("Steve Yzerman", 1063),
                   "points": ("Gordie Howe", 1809)},
        "goalie_season": {"wins": ("Terry Sawchuk", 44, "1950-51"),
                          "shutouts": ("Terry Sawchuk", 12, "1951-52")},
        "goalie_career": {"wins": ("Terry Sawchuk", 350),
                          "shutouts": ("Terry Sawchuk", 85)},
    },
    "Florida Panthers": {
        "season": {"goals": ("Pavel Bure", 59, "2000-01"),
                   "assists": ("Jonathan Huberdeau", 85, "2021-22"),
                   "points": ("Jonathan Huberdeau", 115, "2021-22")},
        "career": {"games": ("Aleksander Barkov", 804),
                   "goals": ("Aleksander Barkov", 286),
                   "assists": ("Aleksander Barkov", 496),
                   "points": ("Aleksander Barkov", 782)},
        "goalie_season": {"wins": ("Sergei Bobrovsky", 39, "2021-22"),
                          "shutouts": ("Roberto Luongo", 7, "2003-04")},
        "goalie_career": {"wins": ("Roberto Luongo", 230),
                          "shutouts": ("Roberto Luongo", 38)},
    },
    "Montreal Canadiens": {
        "season": {"goals": ("Steve Shutt", 60, "1976-77"),
                   "assists": ("Pete Mahovlich", 82, "1974-75"),
                   "points": ("Guy Lafleur", 136, "1976-77")},
        "career": {"games": ("Henri Richard", 1256),
                   "goals": ("Maurice Richard", 544),
                   "assists": ("Guy Lafleur", 728),
                   "points": ("Guy Lafleur", 1246)},
        "goalie_season": {"wins": ("Carey Price", 44, "2014-15"),
                          "shutouts": ("George Hainsworth", 22, "1928-29")},
        "goalie_career": {"wins": ("Carey Price", 361),
                          "shutouts": ("George Hainsworth", 75)},
    },
    "Ottawa Senators": {
        "season": {"goals": ("Dany Heatley", 50, "2005-06"),
                   "assists": ("Jason Spezza", 71, "2005-06"),
                   "points": ("Dany Heatley", 105, "2006-07")},
        "career": {"games": ("Chris Phillips", 1179),
                   "goals": ("Daniel Alfredsson", 426),
                   "assists": ("Daniel Alfredsson", 682),
                   "points": ("Daniel Alfredsson", 1108)},
        "goalie_season": {"wins": ("Patrick Lalime", 39, "2002-03"),
                          "shutouts": ("Patrick Lalime", 8, "2002-03")},
        "goalie_career": {"wins": ("Craig Anderson", 202),
                          "shutouts": ("Patrick Lalime", 30)},
    },
    "Tampa Bay Lightning": {
        "season": {"goals": ("Steven Stamkos", 60, "2011-12"),
                   "assists": ("Nikita Kucherov", 100, "2023-24"),
                   "points": ("Nikita Kucherov", 144, "2023-24")},
        "career": {"games": ("Victor Hedman", 1164),
                   "goals": ("Steven Stamkos", 555),
                   "assists": ("Nikita Kucherov", 723),
                   "points": ("Steven Stamkos", 1137)},
        "goalie_season": {"wins": ("Andrei Vasilevskiy", 44, "2017-18"),
                          "shutouts": ("Andrei Vasilevskiy", 8, "2017-18")},
        "goalie_career": {"wins": ("Andrei Vasilevskiy", 370),
                          "shutouts": ("Andrei Vasilevskiy", 42)},
    },
    "Toronto Maple Leafs": {
        "season": {"goals": ("Auston Matthews", 69, "2023-24"),
                   "assists": ("Doug Gilmour", 95, "1992-93"),
                   "points": ("Doug Gilmour", 127, "1992-93")},
        "career": {"games": ("George Armstrong", 1188),
                   "goals": ("Auston Matthews", 421),
                   "assists": ("Borje Salming", 620),
                   "points": ("Mats Sundin", 987)},
        "goalie_season": {"wins": ("Frederik Andersen", 38, "2017-18"),
                          "shutouts": ("Harry Lumley", 13, "1953-54")},
        "goalie_career": {"wins": ("Turk Broda", 302),
                          "shutouts": ("Turk Broda", 62)},
    },
    "Carolina Hurricanes": {
        "season": {"goals": ("Blaine Stoughton", 56, "1979-80"),
                   "assists": ("Ron Francis", 69, "1989-90"),
                   "points": ("Mike Rogers", 105, "1979-80")},
        "career": {"games": ("Ron Francis", 1186),
                   "goals": ("Ron Francis", 382),
                   "assists": ("Ron Francis", 793),
                   "points": ("Ron Francis", 1175)},
        "goalie_season": {"wins": ("Cam Ward", 39, "2008-09"),
                          "shutouts": ("Arturs Irbe", 6, "1998-99")},
        "goalie_career": {"wins": ("Cam Ward", 318),
                          "shutouts": ("Cam Ward", 27)},
    },
    "Columbus Blue Jackets": {
        "season": {"goals": ("Rick Nash", 41, "2003-04"),
                   "assists": ("Artemi Panarin", 59, "2018-19"),
                   "points": ("Artemi Panarin", 87, "2018-19")},
        "career": {"games": ("Boone Jenner", 808),
                   "goals": ("Rick Nash", 289),
                   "assists": ("Zach Werenski", 330),
                   "points": ("Rick Nash", 547)},
        "goalie_season": {"wins": ("Sergei Bobrovsky", 41, "2016-17"),
                          "shutouts": ("Steve Mason", 10, "2008-09")},
        "goalie_career": {"wins": ("Sergei Bobrovsky", 213),
                          "shutouts": ("Sergei Bobrovsky", 33)},
    },
    "New Jersey Devils": {
        "season": {"goals": ("Brian Gionta", 48, "2005-06"),
                   "assists": ("Scott Stevens", 60, "1993-94"),
                   "points": ("Patrik Elias", 96, "2000-01")},
        "career": {"games": ("Ken Daneyko", 1283),
                   "goals": ("Patrik Elias", 408),
                   "assists": ("Patrik Elias", 617),
                   "points": ("Patrik Elias", 1025)},
        "goalie_season": {"wins": ("Martin Brodeur", 48, "2006-07"),
                          "shutouts": ("Martin Brodeur", 12, "2006-07")},
        "goalie_career": {"wins": ("Martin Brodeur", 688),
                          "shutouts": ("Martin Brodeur", 124)},
    },
    "New York Islanders": {
        "season": {"goals": ("Mike Bossy", 69, "1978-79"),
                   "assists": ("Bryan Trottier", 87, "1978-79"),
                   "points": ("Mike Bossy", 147, "1981-82")},
        "career": {"games": ("Bryan Trottier", 1123),
                   "goals": ("Mike Bossy", 573),
                   "assists": ("Bryan Trottier", 853),
                   "points": ("Bryan Trottier", 1353)},
        "goalie_season": {"wins": ("Jaroslav Halak", 38, "2014-15"),
                          "shutouts": ("Chico Resch", 7, "1975-76")},
        "goalie_career": {"wins": ("Billy Smith", 304),
                          "shutouts": ("Chico Resch", 25)},
    },
    "New York Rangers": {
        "season": {"goals": ("Jaromir Jagr", 54, "2005-06"),
                   "assists": ("Brian Leetch", 80, "1991-92"),
                   "points": ("Jaromir Jagr", 123, "2005-06")},
        "career": {"games": ("Harry Howell", 1160),
                   "goals": ("Rod Gilbert", 406),
                   "assists": ("Brian Leetch", 741),
                   "points": ("Rod Gilbert", 1021)},
        "goalie_season": {"wins": ("Mike Richter", 42, "1993-94"),
                          "shutouts": ("John Ross Roach", 13, "1928-29")},
        "goalie_career": {"wins": ("Henrik Lundqvist", 459),
                          "shutouts": ("Henrik Lundqvist", 64)},
    },
    "Philadelphia Flyers": {
        "season": {"goals": ("Reggie Leach", 61, "1975-76"),
                   "assists": ("Bobby Clarke", 89, "1974-75"),
                   "points": ("Mark Recchi", 123, "1992-93")},
        "career": {"games": ("Bobby Clarke", 1144),
                   "goals": ("Bill Barber", 420),
                   "assists": ("Bobby Clarke", 852),
                   "points": ("Bobby Clarke", 1210)},
        "goalie_season": {"wins": ("Bernie Parent", 47, "1973-74"),
                          "shutouts": ("Bernie Parent", 12, "1973-74")},
        "goalie_career": {"wins": ("Ron Hextall", 240),
                          "shutouts": ("Bernie Parent", 50)},
    },
    "Pittsburgh Penguins": {
        "season": {"goals": ("Mario Lemieux", 85, "1988-89"),
                   "assists": ("Mario Lemieux", 114, "1988-89"),
                   "points": ("Mario Lemieux", 199, "1988-89")},
        "career": {"games": ("Sidney Crosby", 1353),
                   "goals": ("Mario Lemieux", 690),
                   "assists": ("Sidney Crosby", 1062),
                   "points": ("Sidney Crosby", 1724)},
        "goalie_season": {"wins": ("Tom Barrasso", 43, "1992-93"),
                          "shutouts": ("Marc-Andre Fleury", 10, "2014-15")},
        "goalie_career": {"wins": ("Marc-Andre Fleury", 375),
                          "shutouts": ("Marc-Andre Fleury", 44)},
    },
    "Washington Capitals": {
        "season": {"goals": ("Alex Ovechkin", 65, "2007-08"),
                   "assists": ("Dennis Maruk", 76, "1981-82"),
                   "points": ("Dennis Maruk", 136, "1981-82")},
        "career": {"games": ("Alex Ovechkin", 1573),
                   "goals": ("Alex Ovechkin", 929),
                   "assists": ("Nicklas Backstrom", 762),
                   "points": ("Alex Ovechkin", 1687)},
        "goalie_season": {"wins": ("Braden Holtby", 48, "2015-16"),
                          "shutouts": ("Braden Holtby", 9, "2016-17")},
        "goalie_career": {"wins": ("Olaf Kolzig", 301),
                          "shutouts": ("Olaf Kolzig", 35)},
    },
    "Arizona Coyotes": {
        "season": {"goals": ("Teemu Selanne", 76, "1992-93"),
                   "assists": ("Phil Housley", 79, "1992-93"),
                   "points": ("Teemu Selanne", 132, "1992-93")},
        "career": {"games": ("Shane Doan", 1540),
                   "goals": ("Shane Doan", 402),
                   "assists": ("Shane Doan", 570),
                   "points": ("Shane Doan", 972)},
        "goalie_season": {"wins": ("Ilya Bryzgalov", 42, "2009-10"),
                          "shutouts": ("Nikolai Khabibulin", 8, "1998-99")},
        "goalie_career": {"wins": ("Ilya Bryzgalov", 130),
                          "shutouts": ("Mike Smith", 22)},
    },
    "Chicago Blackhawks": {
        "season": {"goals": ("Bobby Hull", 58, "1968-69"),
                   "assists": ("Denis Savard", 87, "1981-82"),
                   "points": ("Denis Savard", 131, "1987-88")},
        "career": {"games": ("Stan Mikita", 1396),
                   "goals": ("Bobby Hull", 604),
                   "assists": ("Stan Mikita", 926),
                   "points": ("Stan Mikita", 1467)},
        "goalie_season": {"wins": ("Ed Belfour", 43, "1990-91"),
                          "shutouts": ("Tony Esposito", 15, "1969-70")},
        "goalie_career": {"wins": ("Tony Esposito", 423),
                          "shutouts": ("Tony Esposito", 76)},
    },
    "Colorado Avalanche": {
        "season": {"goals": ("Michel Goulet", 57, "1982-83"),
                   "assists": ("Peter Stastny", 93, "1981-82"),
                   "points": ("Nathan MacKinnon", 140, "2023-24")},
        "career": {"games": ("Joe Sakic", 1378),
                   "goals": ("Joe Sakic", 625),
                   "assists": ("Joe Sakic", 1016),
                   "points": ("Joe Sakic", 1641)},
        "goalie_season": {"wins": ("Semyon Varlamov", 41, "2013-14"),
                          "shutouts": ("Patrick Roy", 9, "2001-02")},
        "goalie_career": {"wins": ("Patrick Roy", 262),
                          "shutouts": ("Patrick Roy", 37)},
    },
    "Dallas Stars": {
        "season": {"goals": ("Dino Ciccarelli", 55, "1981-82"),
                   "assists": ("Neal Broten", 76, "1985-86"),
                   "points": ("Bobby Smith", 114, "1981-82")},
        "career": {"games": ("Mike Modano", 1459),
                   "goals": ("Mike Modano", 557),
                   "assists": ("Mike Modano", 802),
                   "points": ("Mike Modano", 1359)},
        "goalie_season": {"wins": ("Marty Turco", 41, "2005-06"),
                          "shutouts": ("Marty Turco", 9, "2003-04")},
        "goalie_career": {"wins": ("Marty Turco", 262),
                          "shutouts": ("Marty Turco", 40)},
    },
    "Minnesota Wild": {
        "season": {"goals": ("Kirill Kaprizov", 47, "2021-22"),
                   "assists": ("Kirill Kaprizov", 61, "2021-22"),
                   "points": ("Kirill Kaprizov", 108, "2021-22")},
        "career": {"games": ("Mikko Koivu", 1028),
                   "goals": ("Kirill Kaprizov", 230),
                   "assists": ("Mikko Koivu", 504),
                   "points": ("Mikko Koivu", 709)},
        "goalie_season": {"wins": ("Devan Dubnyk", 40, "2016-17"),
                          "shutouts": ("Niklas Backstrom", 8, "2008-09")},
        "goalie_career": {"wins": ("Niklas Backstrom", 194),
                          "shutouts": ("Niklas Backstrom", 28)},
    },
    "Nashville Predators": {
        "season": {"goals": ("Filip Forsberg", 48, "2023-24"),
                   "assists": ("Roman Josi", 73, "2021-22"),
                   "points": ("Roman Josi", 96, "2021-22")},
        "career": {"games": ("Roman Josi", 1030),
                   "goals": ("Filip Forsberg", 358),
                   "assists": ("Roman Josi", 576),
                   "points": ("Roman Josi", 779)},
        "goalie_season": {"wins": ("Pekka Rinne", 43, "2011-12"),
                          "shutouts": ("Pekka Rinne", 8, "2017-18")},
        "goalie_career": {"wins": ("Pekka Rinne", 369),
                          "shutouts": ("Pekka Rinne", 60)},
    },
    "St. Louis Blues": {
        "season": {"goals": ("Brett Hull", 86, "1990-91"),
                   "assists": ("Adam Oates", 90, "1990-91"),
                   "points": ("Brett Hull", 131, "1990-91")},
        "career": {"games": ("Bernie Federko", 927),
                   "goals": ("Brett Hull", 527),
                   "assists": ("Bernie Federko", 721),
                   "points": ("Bernie Federko", 1073)},
        "goalie_season": {"wins": ("Roman Turek", 42, "1999-2000"),
                          "shutouts": ("Brian Elliott", 9, "2011-12")},
        "goalie_career": {"wins": ("Jordan Binnington", 181),
                          "shutouts": ("Brian Elliott", 25)},
    },
    "Winnipeg Jets": {
        "season": {"goals": ("Ilya Kovalchuk", 52, "2005-06"),
                   "assists": ("Blake Wheeler", 71, "2018-19"),
                   "points": ("Mark Scheifele", 103, "2025-26")},
        "career": {"games": ("Mark Scheifele", 961),
                   "goals": ("Mark Scheifele", 372),
                   "assists": ("Blake Wheeler", 550),
                   "points": ("Mark Scheifele", 907)},
        "goalie_season": {"wins": ("Connor Hellebuyck", 47, "2024-25"),
                          "shutouts": ("Connor Hellebuyck", 8, "2024-25")},
        "goalie_career": {"wins": ("Connor Hellebuyck", 345),
                          "shutouts": ("Connor Hellebuyck", 45)},
    },
    "Anaheim Ducks": {
        "season": {"goals": ("Teemu Selanne", 52, "1997-98"),
                   "assists": ("Ryan Getzlaf", 66, "2008-09"),
                   "points": ("Teemu Selanne", 109, "1996-97")},
        "career": {"games": ("Ryan Getzlaf", 1157),
                   "goals": ("Teemu Selanne", 457),
                   "assists": ("Ryan Getzlaf", 737),
                   "points": ("Ryan Getzlaf", 1019)},
        "goalie_season": {"wins": ("Jean-Sebastien Giguere", 36, "2006-07"),
                          "shutouts": ("Jean-Sebastien Giguere", 8, "2002-03")},
        "goalie_career": {"wins": ("Jean-Sebastien Giguere", 206),
                          "shutouts": ("Jean-Sebastien Giguere", 32)},
    },
    "Calgary Flames": {
        "season": {"goals": ("Lanny McDonald", 66, "1982-83"),
                   "assists": ("Kent Nilsson", 82, "1980-81"),
                   "points": ("Kent Nilsson", 131, "1980-81")},
        "career": {"games": ("Jarome Iginla", 1219),
                   "goals": ("Jarome Iginla", 525),
                   "assists": ("Al MacInnis", 609),
                   "points": ("Jarome Iginla", 1095)},
        "goalie_season": {"wins": ("Miikka Kiprusoff", 45, "2008-09"),
                          "shutouts": ("Miikka Kiprusoff", 10, "2005-06")},
        "goalie_career": {"wins": ("Miikka Kiprusoff", 305),
                          "shutouts": ("Miikka Kiprusoff", 41)},
    },
    "Edmonton Oilers": {
        "season": {"goals": ("Wayne Gretzky", 92, "1981-82"),
                   "assists": ("Wayne Gretzky", 163, "1985-86"),
                   "points": ("Wayne Gretzky", 215, "1985-86")},
        "career": {"games": ("Kevin Lowe", 1037),
                   "goals": ("Wayne Gretzky", 583),
                   "assists": ("Wayne Gretzky", 1086),
                   "points": ("Wayne Gretzky", 1669)},
        "goalie_season": {"wins": ("Cam Talbot", 42, "2016-17"),
                          "shutouts": ("Curtis Joseph", 8, "1997-98")},
        "goalie_career": {"wins": ("Grant Fuhr", 226),
                          "shutouts": ("Tommy Salo", 23)},
    },
    "Los Angeles Kings": {
        "season": {"goals": ("Bernie Nicholls", 70, "1988-89"),
                   "assists": ("Wayne Gretzky", 122, "1990-91"),
                   "points": ("Wayne Gretzky", 168, "1988-89")},
        "career": {"games": ("Anze Kopitar", 1521),
                   "goals": ("Luc Robitaille", 557),
                   "assists": ("Anze Kopitar", 864),
                   "points": ("Anze Kopitar", 1316)},
        "goalie_season": {"wins": ("Jonathan Quick", 40, "2015-16"),
                          "shutouts": ("Jonathan Quick", 10, "2011-12")},
        "goalie_career": {"wins": ("Jonathan Quick", 370),
                          "shutouts": ("Jonathan Quick", 57)},
    },
    "San Jose Sharks": {
        "season": {"goals": ("Jonathan Cheechoo", 56, "2005-06"),
                   "assists": ("Joe Thornton", 92, "2006-07"),
                   "points": ("Macklin Celebrini", 115, "2025-26")},
        "career": {"games": ("Patrick Marleau", 1607),
                   "goals": ("Patrick Marleau", 522),
                   "assists": ("Joe Thornton", 804),
                   "points": ("Patrick Marleau", 1111)},
        "goalie_season": {"wins": ("Evgeni Nabokov", 46, "2007-08"),
                          "shutouts": ("Evgeni Nabokov", 9, "2003-04")},
        "goalie_career": {"wins": ("Evgeni Nabokov", 293),
                          "shutouts": ("Evgeni Nabokov", 50)},
    },
    "Seattle Kraken": {
        "season": {"goals": ("Jared McCann", 40, "2022-23"),
                   "assists": ("Vince Dunn", 50, "2022-23"),
                   "points": ("Jared McCann", 70, "2022-23")},
        "career": {"games": ("Adam Larsson", 409),
                   "goals": ("Jared McCann", 138),
                   "assists": ("Vince Dunn", 174),
                   "points": ("Jared McCann", 283)},
        "goalie_season": {"wins": ("Martin Jones", 27, "2022-23"),
                          "shutouts": ("Martin Jones", 3, "2022-23")},
        "goalie_career": {"wins": ("Philipp Grubauer", 70),
                          "shutouts": ("Joey Daccord", 7)},
    },
    "Utah Hockey Club": {
        "season": {"goals": ("Dylan Guenther", 40, "2025-26"),
                   "assists": ("Clayton Keller", 62, "2025-26"),
                   "points": ("Clayton Keller", 90, "2024-25")},
        "career": {"games": ("Nick Schmaltz", 164),
                   "goals": ("Dylan Guenther", 67),
                   "assists": ("Clayton Keller", 122),
                   "points": ("Clayton Keller", 178)},
        "goalie_season": {"wins": ("Karel Vejmelka", 38, "2025-26"),
                          "shutouts": ("Karel Vejmelka", 2, "2025-26")},
        "goalie_career": {"wins": ("Karel Vejmelka", 64),
                          "shutouts": ("Karel Vejmelka", 3)},
    },
    "Vancouver Canucks": {
        "season": {"goals": ("Pavel Bure", 60, "1992-93"),
                   "assists": ("Henrik Sedin", 83, "2009-10"),
                   "points": ("Henrik Sedin", 112, "2009-10")},
        "career": {"games": ("Henrik Sedin", 1330),
                   "goals": ("Daniel Sedin", 393),
                   "assists": ("Henrik Sedin", 830),
                   "points": ("Henrik Sedin", 1070)},
        "goalie_season": {"wins": ("Roberto Luongo", 47, "2006-07"),
                          "shutouts": ("Roberto Luongo", 9, "2008-09")},
        "goalie_career": {"wins": ("Roberto Luongo", 252),
                          "shutouts": ("Roberto Luongo", 38)},
    },
    "Vegas Golden Knights": {
        "season": {"goals": ("William Karlsson", 43, "2017-18"),
                   "assists": ("Jack Eichel", 66, "2024-25"),
                   "points": ("Jack Eichel", 94, "2024-25")},
        "career": {"games": ("Brayden McNabb", 647),
                   "goals": ("Jonathan Marchessault", 192),
                   "assists": ("Shea Theodore", 302),
                   "points": ("Jonathan Marchessault", 417)},
        "goalie_season": {"wins": ("Marc-Andre Fleury", 35, "2018-19"),
                          "shutouts": ("Marc-Andre Fleury", 8, "2018-19")},
        "goalie_career": {"wins": ("Marc-Andre Fleury", 117),
                          "shutouts": ("Marc-Andre Fleury", 23)},
    },
}
